In [1]:
import pandas as pd
import time
import random
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import classification_report,recall_score,precision_score,roc_auc_score
from sklearn.linear_model import LogisticRegression #LogisticRegression
from sklearn.tree import DecisionTreeClassifier #DecisionTreeRegresor
from sklearn.ensemble import RandomForestClassifier  # RandomForestRegressor
from sklearn.ensemble import AdaBoostClassifier #Adaptive Boost
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.ensemble import GradientBoostingClassifier #Gradient Boost 
from sklearn.svm import SVC #SVC
from sklearn.naive_bayes import GaussianNB #NaiveBayes
from IPython.display import Image  
from sklearn.tree import export_graphviz
from io import StringIO
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r"C:\Users\kisho\DataScience\Machine Learning\Practice\cat2.csv")

In [3]:
data.head()

Unnamed: 0  online_booking  mobile_site_booking  Car_Cancellation  \
0           0               0                    0                 0   
1           1               0                    0                 0   
2           2               0                    0                 0   
3           3               0                    0                 0   
4           4               0                    0                 0   

   from_month  from_datee  weekend  timeOfDay  timeDifference  distance  \
0           1           1        0          6               1      8016   
1           1           1        0          2               7      8015   
2           1           1        0          6               0      8009   
3           1           1        0          1               1      8003   
4           1           1        0          2               2      8024   

   from_cancel_zone  to_cancel_zone  
0                 1               1  
1                 1               1  
2                 1               1  
3                 1               0  
4                 1               1

In [4]:
data = data.drop('Unnamed: 0',axis=1)
data.head(3)

online_booking  mobile_site_booking  Car_Cancellation  from_month  \
0               0                    0                 0           1   
1               0                    0                 0           1   
2               0                    0                 0           1   

   from_datee  weekend  timeOfDay  timeDifference  distance  from_cancel_zone  \
0           1        0          6               1      8016                 1   
1           1        0          2               7      8015                 1   
2           1        0          6               0      8009                 1   

   to_cancel_zone  
0               1  
1               1  
2               1

In [5]:
data.shape

(34292, 11)

In [6]:
data.columns

Index(['online_booking', 'mobile_site_booking', 'Car_Cancellation',
       'from_month', 'from_datee', 'weekend', 'timeOfDay', 'timeDifference',
       'distance', 'from_cancel_zone', 'to_cancel_zone'],
      dtype='object')

In [7]:
names =['online_booking', 'mobile_site_booking', 'Car_Cancellation',
       'from_month', 'from_datee', 'weekend', 'timeOfDay', 'timeDifference',
       'distance', 'from_cancel_zone', 'to_cancel_zone'],

dx = ['Cancel', 'notCancel']

In [8]:
X = data.loc[:,data.columns!='Car_Cancellation'].values
X

array([[   0,    0,    1, ..., 8016,    1,    1],
       [   0,    0,    1, ..., 8015,    1,    1],
       [   0,    0,    1, ..., 8009,    1,    1],
       ...,
       [   1,    0,   11, ..., 7986,    1,    1],
       [   0,    0,   11, ..., 8008,    1,    1],
       [   0,    1,   11, ..., 8005,    1,    1]], dtype=int64)

In [9]:
y = data.Car_Cancellation.values
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
print("Shape of features set X: ",X.shape)
print("Shape of target Y: ",y.shape)

Shape of features set X:  (34292, 10)
Shape of target Y:  (34292,)


In [11]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [12]:
print("Data of training features: ",x_train.shape)
print("Data of testing features: ",x_test.shape)
print("\n")
print("Data of training target: ",y_train.shape)
print("Data of testing target: ",y_test.shape)

Data of training features:  (24004, 10)
Data of testing features:  (10288, 10)


Data of training target:  (24004,)
Data of testing target:  (10288,)


In [13]:
std_scaler = StandardScaler()
x_train = std_scaler.fit_transform(x_train)
x_test = std_scaler.fit_transform(x_test)
x_train

array([[ 1.31915983e+00, -2.26462845e-01, -8.34554842e-01, ...,
         5.60764328e-04,  1.56401644e-01,  1.17275296e-01],
       [-7.58058258e-01, -2.26462845e-01,  1.84158303e-01, ...,
         9.77538848e-01,  1.56401644e-01,  1.17275296e-01],
       [-7.58058258e-01, -2.26462845e-01, -8.34554842e-01, ...,
         8.68985728e-01,  1.56401644e-01,  1.17275296e-01],
       ...,
       [-7.58058258e-01, -2.26462845e-01, -4.94983794e-01, ...,
         4.34773246e-01,  1.56401644e-01,  1.17275296e-01],
       [ 1.31915983e+00, -2.26462845e-01, -1.85326799e+00, ...,
        -3.25098597e-01, -3.80379358e+00,  1.17275296e-01],
       [-7.58058258e-01, -2.26462845e-01,  1.84158303e-01, ...,
         8.68985728e-01,  1.56401644e-01,  1.17275296e-01]])